# Schema for the configuration files of the micro module.

micro.type.*:
  type: config_entity
  label: 'Micro type'
  mapping:
    type:
      type: string
      label: 'Machine-readable name'
    id:
      type: string
      label: 'ID'
